version: '3.8'
services:
  db:
    image: mysql:8-debian
    environment:
      MYSQL_DATABASE: 'pagaew'
      MYSQL_ROOT_PASSWORD: 'pagaewweagap'
      # totally insecure
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
